### ISSUE TITLE
ModuleNotFoundError: No module named 'synapse'

### ISSUE THREAD

**Issue by re-do-ne** [AVENTER-UG/docker-matrix#72]
It seems that starting with tag [v1.111.1](https://registry.hub.docker.com/layers/avhost/docker-matrix/v1.111.1/images/sha256-4e9cffbf14319ce68e86dc07f3157473fed874b034bc1aff6afa2ddf6a0f22fe?context=explore), the server will not properly start anymore:
```
-=> start turn
-=> start matrix
Cannot create pid file: /var/run/turnserver.pid: Permission denied
/usr/bin/python3: Error while finding module specification for 'synapse.app.homeserver' (ModuleNotFoundError: No module named 'synapse')
```
Reverting back to tag [v1.111.0](https://registry.hub.docker.com/layers/avhost/docker-matrix/v1.111.0/images/sha256-4d9e27ba532a09217f67635e531dbb5a395a0bd0311885f6e1ee5f28cfad32e6?context=explore) works without issues.

**Comment by mvgorcum** [comment]
I'm unable to reproduce this, could you pull v1.111.1 again and see if that fixes it?

Alternatively you could use mvgorcum/docker-matrix:v1.112.0 (I don't think andreas pushed v1.112.0 yet)

**Comment by andreaspeters** [comment]
v1.111.1 and v1.111 are the same image. Your issue @re-do-ne  we had with v1.111.0 but we fixed it. So I think @mvgorcum is right and it's more a caching issue. So please pull v1.111 again. btw, v1.112.0 is available since 9 hours. :sweat_smile:

**Comment by re-do-ne** [comment]
Unfortunately, after docker rmi'ing all post-1.111.0 images and force-recreating the container on 1.112, it pulls in all new layers but still fails to properly start with the same message (same thing happens on mvgorcum/docker-matrix:v1.112.0 unfortunately):
```
$ grep 'image' docker-compose.yml 
    image: 'avhost/docker-matrix:v1.112'
$ docker compose up -d --force-recreate
[+] Running 17/17
 ✔ synapse Pulled                                                                                                                                                                                                          29.8s 
   ✔ 9e24c9a1f71e Pull complete                                                                                                                                                                                             3.7s 
   ✔ d3a35a710761 Pull complete                                                                                                                                                                                             3.7s 
   ✔ a5e809ac87db Pull complete                                                                                                                                                                                             3.8s 
   ✔ 2e46d0f5d4ae Pull complete                                                                                                                                                                                             3.8s 
   ✔ 29537ad9a3df Pull complete                                                                                                                                                                                             3.8s 
   ✔ bf70454020d3 Pull complete                                                                                                                                                                                             4.3s 
   ✔ 58ed86362c23 Pull complete                                                                                                                                                                                             4.9s 
   ✔ 467a14d62616 Pull complete                                                                                                                                                                                            11.3s 
   ✔ 06bcd3f34f2b Pull complete                                                                                                                                                                                            11.3s 
   ✔ 2ef263153277 Pull complete                                                                                                                                                                                            11.3s 
   ✔ 1721c5436836 Pull complete                                                                                                                                                                                            11.4s 
   ✔ 7903a3fd3c22 Pull complete                                                                                                                                                                                            19.8s 
   ✔ 858be180fa6a Pull complete                                                                                                                                                                                            19.8s 
   ✔ b45961c3b4c5 Pull complete                                                                                                                                                                                            27.9s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                                            28.0s 
   ✔ c2bcd915ef09 Pull complete                                                                                                                                                                                            28.0s 
[+] Running 1/1
 ✔ Container matrix  Started
$ docker logs matrix
-=> start turn
-=> start matrix
/usr/bin/python3: Error while finding module specification for 'synapse.app.homeserver' (ModuleNotFoundError: No module named 'synapse')
Cannot create pid file: /var/run/turnserver.pid: Permission denied
```
Going back to 1.111.0 makes everything work as before (note that both 1.111 and 1.111.1 also fail, only 1.111.0 and earlier tags seem to work for me).

**Comment by andreaspeters** [comment]
strange, I tried it on a clean new vm and do not get these error. Can you show us the docker-compose file (but do not forget to replace critical information)?

**Comment by re-do-ne** [comment]
> strange, I tried it on a clean new vm and do not get these error. Can you show us the docker-compose file (but do not forget to replace critical information)?

Sure thing!
Nothing special as far as I can tell:
```
services:
  synapse:
    image: 'avhost/docker-matrix:v1.111.0'
    container_name: matrix
    restart: unless-stopped
    user: '1000:996'
    working_dir: '/data'
    environment:
      - MATRIX_UID=1000
      - MATRIX_GID=996
    volumes:
      - '/docker/synapse/data:/data'
    ports:
      - '8448:8448'
    command: 'start'
 ```
The /data dir also just contains a pretty standard homeserver.yaml, the db and some logs.

//edit
When comparing the containers, it seems permissions on the /matrix dir have changed. 1.111.1 and up:
```
I have no name!@a1b6d2dd9729:/data$ ls -liad /matrix
2923026 drwx------ 1 matrix matrix 4096 Jul 31 09:03 /matrix
```
1.111.0:
```
I have no name!@4b2582bf957d:/data$ ls -liad /matrix
2885420 drwxr-xr-x 1 matrix matrix 4096 Jul 16 13:54 /matrix
```
So when using a custom UID, the newer tagged versions don't allow access (outside of the default 991 matrix UID).

**Comment by andreaspeters** [comment]
Remove the "user" item of the docker-compose file. That will fix the issue. It seams that these mechanism is broken. So, the default user and group would be 991. That means you have to change the owner of the matrix files under /docker/synapse/data and of course be sure that these user have write and execute permissions at /docker/synapse.
Also do not forget to remove the MATRIX_UID/GID env items. 

Sorry for that failure. :-(

**Comment by re-do-ne** [comment]
Oh that's very unfortunate, guess the MATRIX_UID/GID env vars are entirely unusable from now on then.

Wouldn't it be better to take those env vars into consideration and simply chown the relevant dirs using the provided values (or perhaps even usermod the matrix user to the given UID value)?

**Comment by andreaspeters** [comment]
The MATRIX_UID/GID vars still works well. The data files will get (during the first genrate command) there ids/guid's. But because of python env (I guess) it does not work to change the users process id.

**Comment by re-do-ne** [comment]
Ah yes, that makes sense. Thanks.

Wouldn't simply usermod'ing the matrix user to the MATRIX_UID also solve the issue, while still allowing the use of differing ownership on mounted volumes? Or perhaps that causes breakage on another level?

**Comment by enfyrneaux** [comment]
I resorted to `chown -Rf 991:991 /my/data/mount` to get mine back up.

**Comment by wkelton** [comment]
I also ran into this. Reverted to 1.111.0 for now.

I set `user:` in my compose to very specific user and group id. I do _not_ set MATRIX_UID/GUID.

2 questions:

1. Will this new behavior be changed back to how it was working previously?
2. What is the recommended way to achieve these 2 goals:
    1. Run services as a non-privileged user/group
    2. Ownership of `/data` volume configurable to a specific user/group

**Comment by andreaspeters** [comment]
Hi Will @wkelton!

First of all, I have to understand why that happen. My first thought was python-venv. But we use it since v1.77.0. 

To 1: The goal would be to restore the previously behavior.

To 2: To your second question. I'm not 100% sure if I understand you correctly. Inside of the docker-matrix container we already use a non-privileged user.

**Comment by andreaspeters** [comment]
I think I fixed it. Please try out docker-matrix:latest (it's synapse v1.112.0).

**Comment by wkelton** [comment]
Thanks Andreas!

Confirmed that it is working for me with latest. (Note: I tried v1.112.0 after deleting the image locally, but got the same sha after repulling and the problem still happened.)

OK, so after looking at start.sh and Dockerfile, I think I understand the user settings.
1. If `user` is not changed at docker/compose level, `data` volume's permissions will be configured with `$MATRIX_UID:$MATRIX_GID` and the homeserver will be started under the `matrix` user which is created with `$MATRIX_UID:$MATRIX_GID`
2. If `user` is set, no permissions will be changed and the homeserver will be run under the docker provided userid

I assume that you advise option 1?

It seems like it would be easy going from option 2 to 1 by removing `user` setting and providing the `MATRIX_UID` `MATRIX_GID` env vars.

**Comment by andreaspeters** [comment]
Thanks for feedback. Happy to hear that it's working for you again. How about @re-do-ne ?

@wkelton If you add "user" then I also recommend to set `MATRIX_UID/ID`. Btw, we are not so happy about that way at all. But many peoples use it so I prefer to keep it like that.
